# Generated by Django 5.2.17 on 2026-09-04 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('libelle', models.CharField(max_length=100, verbose_name='libellé')),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='libellé')),
                ('code_iso', models.CharField(max_length=3, unique=True, verbose_name='code ISO')),
            ],
            options={
                'verbose_name': 'pays',
                'verbose_name_plural': 'pays',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('libelle', models.CharField(max_length=100, verbose_name='libellé')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='geographie.district', verbose_name='district')),
            ],
            options={
                'verbose_name': 'commune',
                'verbose_name_plural': 'communes',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('libelle', models.CharField(max_length=100, verbose_name='libellé')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='geographie.pays', verbose_name='pays')),
            ],
            options={
                'verbose_name': 'région',
                'verbose_name_plural': 'régions',
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='geographie.region', verbose_name='région'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('libelle', models.CharField(max_length=100, verbose_name='libellé')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villages', to='geographie.commune', verbose_name='commune')),
            ],
            options={
                'verbose_name': 'village',
                'verbose_name_plural': 'villages',
                'ordering': ['libelle'],
            },
        ),
        migrations.AddConstraint(
            model_name='commune',
            constraint=models.UniqueConstraint(fields=('libelle', 'district'), name='commune_unique_dans_district'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('libelle', 'pays'), name='region_unique_dans_pays'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('libelle', 'region'), name='district_unique_dans_region'),
        ),
        migrations.AddConstraint(
            model_name='village',
            constraint=models.UniqueConstraint(fields=('libelle', 'commune'), name='village_unique_dans_commune'),
        ),
    ]
