# Generated by Django 5.2.17 on 2026-09-04 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geographie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('archive', models.BooleanField(default=False, verbose_name='archivé')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=32, verbose_name='téléphone')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='profession')),
                ('nombre_enfants', models.PositiveSmallIntegerField(default=0, verbose_name="nombre d'enfants")),
                ('situation_familiale', models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('veuf', 'Veuf(ve)'), ('divorce', 'Divorcé(e)')], max_length=20, verbose_name='situation familiale')),
                ('revenu', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='revenu mensuel')),
                ('photo', models.ImageField(blank=True, upload_to='beneficiaires/photos/', verbose_name='photo')),
                ('numero_cin', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='numéro CIN')),
                ('numero_passeport', models.CharField(blank=True, max_length=32, verbose_name='numéro de passeport')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('decede', 'Décédé(e)'), ('demenage', 'Déménagé(e)')], default='actif', max_length=20, verbose_name='statut')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaires', to='geographie.village', verbose_name='village')),
            ],
            options={
                'verbose_name': 'bénéficiaire',
                'verbose_name_plural': 'bénéficiaires',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['nom', 'prenom'], name='beneficiaire_nom_prenom')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('numero_cin__isnull', False)), fields=('numero_cin',), name='cin_unique_si_renseigne')],
            },
        ),
    ]
