# Generated by Django 5.2.17 on 2026-09-04 11:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaires', '0001_initial'),
        ('geographie', '0001_initial'),
        ('projets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneAide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('archive', models.BooleanField(default=False, verbose_name='archivé')),
                ('code', models.CharField(max_length=32, verbose_name='code')),
                ('libelle', models.CharField(max_length=150, verbose_name='libellé')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='année')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='budget')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('etat', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='état')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campagnes', to='projets.projet', verbose_name='projet')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campagnes_animees', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
            ],
            options={
                'verbose_name': 'campagne',
                'verbose_name_plural': 'campagnes',
                'ordering': ['-annee', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='DistributionAide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('archive', models.BooleanField(default=False, verbose_name='archivé')),
                ('date_distribution', models.DateField(verbose_name='date de distribution')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='quantité')),
                ('unite', models.CharField(default='unité', max_length=32, verbose_name='unité')),
                ('observation', models.TextField(blank=True, verbose_name='observation')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='beneficiaires.beneficiaire', verbose_name='bénéficiaire')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='campagnes.campagneaide', verbose_name='campagne')),
                ('saisie_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='saisi par')),
                ('village', models.ForeignKey(help_text="Lieu où l'aide a été remise, qui peut différer du village de résidence du bénéficiaire.", on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='geographie.village', verbose_name='village de distribution')),
            ],
            options={
                'verbose_name': 'distribution',
                'verbose_name_plural': 'distributions',
                'ordering': ['-date_distribution'],
            },
        ),
        migrations.AddConstraint(
            model_name='campagneaide',
            constraint=models.UniqueConstraint(condition=models.Q(('archive', False)), fields=('code',), name='campagne_code_unique_si_active'),
        ),
        migrations.AddIndex(
            model_name='distributionaide',
            index=models.Index(fields=['campagne', 'village'], name='distribution_campagne_village'),
        ),
        migrations.AddConstraint(
            model_name='distributionaide',
            constraint=models.UniqueConstraint(condition=models.Q(('archive', False)), fields=('beneficiaire', 'campagne'), name='distribution_unique_par_campagne'),
        ),
    ]
