# Generated by Django 5.2.17 on 2026-09-04 11:22

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campagneaide',
            options={'base_manager_name': 'tous', 'ordering': ['-annee', 'libelle'], 'verbose_name': 'campagne', 'verbose_name_plural': 'campagnes'},
        ),
        migrations.AlterModelOptions(
            name='distributionaide',
            options={'base_manager_name': 'tous', 'ordering': ['-date_distribution'], 'verbose_name': 'distribution', 'verbose_name_plural': 'distributions'},
        ),
        migrations.AlterModelManagers(
            name='campagneaide',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('tous', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='distributionaide',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('tous', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='distributionaide',
            name='annulee_par',
            field=models.ForeignKey(blank=True, help_text='Renseigné uniquement si cette distribution a été annulée.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributions_annulees', to=settings.AUTH_USER_MODEL, verbose_name='annulée par'),
        ),
        migrations.AddField(
            model_name='distributionaide',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date d'annulation"),
        ),
    ]
