# Generated by Django 5.2.17 on 2026-09-04 10:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geographie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='libellé')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': "type d'action",
                'verbose_name_plural': "types d'action",
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('archive', models.BooleanField(default=False, verbose_name='archivé')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='code')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('budget_prevu', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='budget prévu')),
                ('budget_consomme', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='budget consommé')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('etat', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='planifie', max_length=20, verbose_name='état')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='geographie.region', verbose_name='région')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets_diriges', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('type_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='projets.typeaction', verbose_name="type d'action")),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['-date_debut', 'code'],
            },
        ),
    ]
